import Head from 'next/head';
import Image from 'next/image';
import styles from './index.module.css';
import { casualList } from '../data/casuals';
import ColorBox from '../components/ColorBox';
import { useEffect, useState } from 'react';

export default function Home() {
    const [listOfCasuals, setListOfCasuals] = useState([]);

    useEffect(() => {
        const sortedList = casualList.sort((a, b) => {
            if (a.name > b.name) return 1;
            if (a.name < b.name) return -1;
            return 0;
        });
        setListOfCasuals([...sortedList]);
    }, []);

    const sortByDate = (date) => {
        const sortedList = casualList.sort((a, b) => {
            if (a.availability[date] > b.availability[date]) return -1;
            if (a.availability[date] < b.availability[date]) return 1;
            return 0;
        });
        setListOfCasuals([...sortedList]);
    };

    const sortByKla = () => {
        const sortedList = casualList.sort((a, b) => {
            if (a.kla > b.kla) return 1;
            if (a.kla < b.kla) return -1;
            return 0;
        });
        setListOfCasuals([...sortedList]);
    };

    const sortByName = () => {
        const sortedList = casualList.sort((a, b) => {
            if (a.name > b.name) return 1;
            if (a.name < b.name) return -1;
            return 0;
        });
        setListOfCasuals([...sortedList]);
    };

    return (
        <div className={styles.container}>
            <Head>
                <title>Casuals List</title>
                <meta name='description' content='Generated by RB' />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <main className={styles.main}>
                <h2>List of Casuals</h2>
                <div className={styles.casuals}>
                    <div className={styles.sortHeader} onClick={sortByName}>
                        Name
                    </div>
                    <div className={styles.sortHeader} onClick={sortByKla}>
                        KLA
                    </div>
                    <div className={styles.grid}>
                        <div className={styles.sortHeader} onClick={() => sortByDate('monday')}>
                            Mon
                        </div>
                        <div className={styles.sortHeader} onClick={() => sortByDate('tuesday')}>
                            Tues
                        </div>
                        <div className={styles.sortHeader} onClick={() => sortByDate('wednesday')}>
                            Wed
                        </div>
                        <div className={styles.sortHeader} onClick={() => sortByDate('thursday')}>
                            Thurs
                        </div>
                        <div className={styles.sortHeader} onClick={() => sortByDate('friday')}>
                            Fri
                        </div>
                    </div>
                </div>

                {listOfCasuals.map((teacher, i) => {
                    return (
                        <div key={i} className={styles.casuals}>
                            <div>{teacher.name}</div>
                            <div>{teacher.kla}</div>
                            <div className={styles.grid}>
                                <div>
                                    {teacher.availability.monday ? (
                                        <ColorBox available={true} />
                                    ) : (
                                        <ColorBox available={false} />
                                    )}
                                </div>
                                <div>
                                    {teacher.availability.tuesday ? (
                                        <ColorBox available />
                                    ) : (
                                        <ColorBox available={false} />
                                    )}
                                </div>
                                <div>
                                    {teacher.availability.wednesday ? (
                                        <ColorBox available />
                                    ) : (
                                        <ColorBox available={false} />
                                    )}
                                </div>
                                <div>
                                    {teacher.availability.thursday ? (
                                        <ColorBox available />
                                    ) : (
                                        <ColorBox available={false} />
                                    )}
                                </div>
                                <div>
                                    {teacher.availability.friday ? (
                                        <ColorBox available />
                                    ) : (
                                        <ColorBox available={false} />
                                    )}
                                </div>
                            </div>
                        </div>
                    );
                })}
            </main>
        </div>
    );
}
